from app.prompts import BASE_PROMPT_EVALUATOR
from app.runpod_agent import query_llm
import logging
from dotenv import load_dotenv
import os
import requests
import re

load_dotenv()

RUNPOD_API_KEY = os.getenv("RUNPOD_API_KEY")
RUNPOD_ENDPOINT = os.getenv("RUNPOD_ENDPOINT")

HEADERS = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {RUNPOD_API_KEY}"
}

logger = logging.getLogger(__name__)


def evaluator_agent(generator_response: str):
    """
    Calls the Runpod LLM to evaluate a generated MCQ.
    Args:
        generator_response (str): The full MCQ in text format (question + options + solution)
    Returns:
        Tuple[str, str]: Evaluation report (raw text), token usage (placeholder)
    """
    evaluation_prompt = f"""
    You are an evaluator agent tasked with assessing the quality of questions generated by a teaching assistant.
    This question will be used in a critical test where master's level students will appear.
    Your role is to analyze the question and provide a structured evaluation based on the following parameters:

    1. Question Quality: Is the question framed correctly? Check the overall structure of the question and also check if the question reveals a lot of information that it reveals the correct options easily.
       Output: Generate a report.

    2. Correct Answer Validity: Is the provided correct answer actually correct based on the context? Check the Solution if it's correct.
       Output: Generate a report.

    3. Option Differentiation: Are the options sufficiently different from each other?
       Output: Rate on a scale of 1-5, where:
        1 = Options are too similar, making the question ambiguous
        3 = Options have an appropriate level of differentiation
        5 = Options are too different, making the question too easy

    Provide your evaluation in a structured format, including a brief explanation for each rating.
    If there are any notable issues or suggestions for improvement, include them in your evaluation.

    {generator_response}
    """.strip()

    messages = [
        {"role": "system", "content": BASE_PROMPT_EVALUATOR},
        {"role": "user", "content": evaluation_prompt}
    ]

    try:
        # Correct RunPod API format
        api_payload = {
            "input": {
                "messages": messages,
                "sampling_params": {
                    "temperature": 0.7,
                    "max_tokens": 4096
                }
            }
        }

        logger.info("Querying Runpod model: %s", "runpod-llm")
        response = requests.post(RUNPOD_ENDPOINT, headers=HEADERS, json=api_payload)
        response.raise_for_status()
        response_json = response.json()
        
        if "output" not in response_json:
            logger.error("Runpod response missing 'output' field: %s", response_json)
            return None, None

        response_text = response_json["output"]
        
        # Clean up the response by removing <think> and <raw> tags
        clean_response = re.sub(r'<think>.*?</think>', '', response_text, flags=re.DOTALL)
        clean_response = re.sub(r'<raw>.*?</raw>', '', clean_response, flags=re.DOTALL)
        
        logger.info("Evaluator response: %s", clean_response)
        
        # Assuming we want to return the clean evaluator feedback and token usage placeholder
        return clean_response, "N/A"  # Token tracking not supported by Runpod yet

    except Exception as e:
        logger.exception("Exception in evaluator_agent:")
        return None, None
