from app.prompts import BASE_PROMPT_EVALUATOR
from app.runpod_agent import query_llm
import logging
from dotenv import load_dotenv
import os
import requests
import re

load_dotenv()

RUNPOD_API_KEY = os.getenv("RUNPOD_API_KEY")
RUNPOD_ENDPOINT = os.getenv("RUNPOD_ENDPOINT")

HEADERS = {
    "Content-Type": "application/json",
    "Authorization": f"Bearer {RUNPOD_API_KEY}"
}

logger = logging.getLogger(__name__)


def evaluator_agent(generator_response: str, question_type: str = "mcq"):
    """
    Calls the Runpod LLM to evaluate a generated question (MCQ, numerical, or subjective).

    Args:
        generator_response (str): Full question and solution text.
        question_type (str): One of 'mcq', 'numerical', or 'subjective'.

    Returns:
        Tuple[str, str]: Evaluation report (raw text), token usage (placeholder)
    """

    if question_type == "mcq":
        evaluation_prompt = f"""
You are an evaluator agent tasked with assessing the quality of a multiple-choice question (MCQ) generated by a teaching assistant.
This question will be used in a critical test for master's level students.

Evaluate the question based on:

1. Question Quality: Is the question framed clearly and does not leak the answer?
2. Correct Answer Validity: Is the provided correct answer actually correct?
3. Option Differentiation: Are the options clearly distinct?

Return your evaluation in this format:
{{
  "Reasoning": "<Short explanation>",
  "Decision": "<'Question' | 'Solution' | 'Options' | 'None'>"
}}

{generator_response}
        """.strip()

    elif question_type == "numerical":
        evaluation_prompt = f"""
You are an evaluator agent tasked with assessing the quality of a numerical question generated by a teaching assistant.
This question will be used in a critical test for master's level students.

Evaluate the question based on:

1. Question Quality: Is the numerical problem framed clearly and unambiguously?
2. Solution Correctness: Is the numerical answer correct and supported by proper reasoning?
3. Clarity: Is the question appropriate for the academic level?

Return your evaluation in this format:
{{
  "Reasoning": "<Short explanation>",
  "Decision": "<'Question' | 'Solution' | 'None'>"
}}

{generator_response}
        """.strip()

    elif question_type == "subjective":
        evaluation_prompt = f"""
You are an evaluator agent tasked with assessing the quality of a subjective (short or long answer) question generated by a teaching assistant.
This question will be used in a critical test for master's level students.

Evaluate the question based on:

1. Conceptual Depth: Does the question test deep understanding or critical thinking?
2. Clarity: Is it clearly worded and appropriate for the student level?
3. Answer Completeness: Does the provided answer cover the essential points?

Return your evaluation in this format:
{{
  "Reasoning": "<Short explanation>",
  "Decision": "<'Question' | 'Solution' | 'None'>"
}}

{generator_response}
        """.strip()

    else:
        raise ValueError(f"Unsupported question_type: {question_type}")

    messages = [
        {"role": "system", "content": BASE_PROMPT_EVALUATOR},
        {"role": "user", "content": evaluation_prompt}
    ]

    try:
        api_payload = {
            "input": {
                "messages": messages,
                "sampling_params": {
                    "temperature": 0.7,
                    "max_tokens": 4096
                }
            }
        }

        logger.info("Querying Runpod model: %s", "runpod-llm")
        response = requests.post(RUNPOD_ENDPOINT, headers=HEADERS, json=api_payload)
        response.raise_for_status()
        response_json = response.json()

        if "output" not in response_json:
            logger.error("Runpod response missing 'output' field: %s", response_json)
            return None, None

        response_text = response_json["output"]
        response_text = response_text[0]['choices'][0]['tokens'][0]

        # Clean the response (optional, in case LLM adds tags)
        clean_response = re.sub(r'<think>.*?</think>', '', response_text, flags=re.DOTALL)
        clean_response = re.sub(r'<raw>|</raw>', '', clean_response, flags=re.IGNORECASE).strip()

        logger.info("Evaluator response: %s", clean_response)

        return clean_response, "N/A"

    except Exception as e:
        logger.exception("Exception in evaluator_agent:")
        return None, None
