# evaluator.py

from app.runpod_agent import query_llm
from utils.logger import logger
import ast

def evaluate_mcq(mcq_response: dict) -> tuple:
    eval_prompt = f"""
You are an evaluator agent tasked with assessing the quality of questions generated by a teaching assistant.
This question will be used in a critical test where masters-level students will appear.

Evaluate the following:
1. Question Quality
2. Correctness of Answer and Solution
3. Option Differentiation

Provide structured evaluation with reasoning and a decision:
Output Format (dictionary):
{{
  "Reasoning": "Explain quality issues, if any.",
  "Decision": "Question" or "Solution" or "Options" or "None"
}}

Input:
{mcq_response}
"""

    try:
        logger.info("Evaluating MCQ response...")
        eval_response = query_llm(eval_prompt)

    # 🔍 If nested Runpod format, extract actual string
        if isinstance(eval_response, dict) and "choices" in eval_response:
            eval_response = eval_response["choices"][0]["tokens"][0]

        result = ast.literal_eval(eval_response)

    # ✅ Ensure result is a dict
        if isinstance(result, list):
            result = result[0] if result and isinstance(result[0], dict) else {"Reasoning": "Invalid format", "Decision": "None"}

        decision = result.get("Decision", "None")
        return result, decision

    except Exception as e:
        logger.exception("Evaluator failed to parse response.")
        return {"Reasoning": "Evaluator crashed.", "Decision": "None"}, "None"